-- =============================================================================
-- AplosCRM — Seed Data: 25 Produce Product Definitions
-- Run after product_definitions table has been created.
-- owner_id=1 assumes the first registered user.
-- =============================================================================

INSERT INTO product_definitions (
    product_name, sku, product_description,
    product_family, product_type, is_active, lifecycle_status,
    list_price, currency, unit_cost, unit_of_measure,
    pricing_model, tax_category,
    subscription_term_months, usage_metrics,
    owner_id
)
VALUES

('Organic Fuji Apples',
 'PRD-00001', 'Premium organic Fuji apples sourced from Washington State. Crisp, sweet flavor ideal for fresh eating and retail display.',
 'Hardware', 'Inventory', 1, 'Activated',
 42.00, 'USD', 26.00, 'Box',
 'Flat', 'Standard',
 NULL, '40 lb box, approx. 88–100 count',
 1),

('Navel Oranges — 56 ct',
 'PRD-00002', 'California-grown navel oranges, seedless and easy to peel. Packed 56 count per carton for foodservice and grocery.',
 'Hardware', 'Inventory', 1, 'Activated',
 38.50, 'USD', 22.00, 'Box',
 'Flat', 'Standard',
 NULL, '40 lb carton, 56 count',
 1),

('Romaine Lettuce Hearts — 3pk',
 'PRD-00003', 'Hydroponic romaine hearts, triple-washed and ready to use. Consistent sizing and long shelf life.',
 'Hardware', 'Inventory', 1, 'Activated',
 28.00, 'USD', 16.50, 'Box',
 'Flat', 'Standard',
 NULL, '12 x 3-pack per case',
 1),

('Seedless Red Grapes',
 'PRD-00004', 'Premium California seedless red grapes, 18 lb clamshell case. Firm texture and high Brix sugar content.',
 'Hardware', 'Inventory', 1, 'Activated',
 54.00, 'USD', 34.00, 'Box',
 'Flat', 'Standard',
 NULL, '18 lb case',
 1),

('Organic Baby Spinach',
 'PRD-00005', 'USDA Certified Organic baby spinach, pre-washed and triple-rinsed. Available in bulk and retail clamshells.',
 'Hardware', 'Inventory', 1, 'Activated',
 62.00, 'USD', 40.00, 'Box',
 'Flat', 'Standard',
 NULL, '4 x 5 lb bags per case',
 1),

('Beefsteak Tomatoes',
 'PRD-00006', 'Large vine-ripened beefsteak tomatoes grown in Florida greenhouses. Consistent color and firm flesh for slicing.',
 'Hardware', 'Inventory', 1, 'Activated',
 32.00, 'USD', 19.00, 'Box',
 'Flat', 'Standard',
 NULL, '25 lb box, 2-layer pack',
 1),

('Yellow Onions — 50 lb Sack',
 'PRD-00007', 'Dry yellow onions, medium-large bulbs, suitable for foodservice and retail. Strong flavor profile for cooking.',
 'Hardware', 'Inventory', 1, 'Activated',
 22.00, 'USD', 11.00, 'Each',
 'Flat', 'Standard',
 NULL, '50 lb mesh sack',
 1),

('Russet Potatoes — 50 lb',
 'PRD-00008', 'Idaho-certified russet potatoes, size 70 count. High starch content, ideal for baking, frying, and mashing.',
 'Hardware', 'Inventory', 1, 'Activated',
 24.00, 'USD', 13.00, 'Each',
 'Flat', 'Standard',
 NULL, '50 lb carton, size 70',
 1),

('Strawberries — 8 x 1 lb Flat',
 'PRD-00009', 'Fresh California strawberries, Grade A, bright red with no white shoulders. Peak season availability March–June.',
 'Hardware', 'Inventory', 1, 'Activated',
 30.00, 'USD', 18.00, 'Box',
 'Flat', 'Standard',
 NULL, '8 x 1 lb clamshells per flat',
 1),

('Broccoli Crowns',
 'PRD-00010', 'Fresh-cut broccoli crowns, trimmed and pre-iced. Sourced from Salinas Valley. Consistent dark green color.',
 'Hardware', 'Inventory', 1, 'Activated',
 36.00, 'USD', 21.00, 'Box',
 'Flat', 'Standard',
 NULL, '20 lb box',
 1),

('Avocados — Hass 48 ct',
 'PRD-00011', 'Premium Hass avocados from Mexico, size 48. Uniform maturity profile, ideal for retail or guacamole production.',
 'Hardware', 'Inventory', 1, 'Activated',
 58.00, 'USD', 36.00, 'Box',
 'Flat', 'Standard',
 NULL, '25 lb case, 48 count',
 1),

('Blueberries — 12 x 6 oz',
 'PRD-00012', 'Highbush blueberries, domestic and imported seasonal supply. Large berry size, firm texture, low moisture.',
 'Hardware', 'Inventory', 1, 'Activated',
 44.00, 'USD', 28.00, 'Box',
 'Flat', 'Standard',
 NULL, '12 x 6 oz clamshells per case',
 1),

('Green Bell Peppers',
 'PRD-00013', 'Uniform extra-large green bell peppers. Thick walls, mild flavor. Excellent for retail display and foodservice prep.',
 'Hardware', 'Inventory', 1, 'Activated',
 28.00, 'USD', 16.00, 'Box',
 'Flat', 'Standard',
 NULL, '25 lb carton, XL size',
 1),

('Celery — 24 ct',
 'PRD-00014', 'Full stalks of California celery, 24 count per crate. Crisp, pale green, trimmed to uniform length.',
 'Hardware', 'Inventory', 1, 'Activated',
 34.00, 'USD', 19.50, 'Box',
 'Flat', 'Standard',
 NULL, '60 lb crate, 24 count',
 1),

('Seedless Watermelon — Bin',
 'PRD-00015', 'Jumbo seedless watermelons, Crimson Sweet variety. Average 18–22 lb per melon. Summer seasonal program available.',
 'Hardware', 'Inventory', 1, 'Activated',
 120.00, 'USD', 72.00, 'Each',
 'Flat', 'Standard',
 NULL, 'Approx. 1,200 lb bin, 55–60 melons',
 1),

('Organic Carrots — 25 lb',
 'PRD-00016', 'USDA Organic whole carrots, peeled and topped. Consistent sizing at 8–9 inches. Year-round Grimmway Farms supply.',
 'Hardware', 'Inventory', 1, 'Activated',
 38.00, 'USD', 22.00, 'Box',
 'Flat', 'Standard',
 NULL, '25 lb bag',
 1),

('Iceberg Lettuce — 24 ct',
 'PRD-00017', 'Standard pack iceberg lettuce, 24 heads per carton. Consistent head weight of 2–2.5 lb. High-volume retail item.',
 'Hardware', 'Inventory', 1, 'Activated',
 26.00, 'USD', 14.50, 'Box',
 'Flat', 'Standard',
 NULL, '50 lb carton, 24 count',
 1),

('Cherry Tomatoes — 12 x 1 pt',
 'PRD-00018', 'Mixed cherry tomato blend — red, yellow, and orange. Vine-sweet, retail-ready pint containers.',
 'Hardware', 'Inventory', 1, 'Activated',
 36.00, 'USD', 22.00, 'Box',
 'Flat', 'Standard',
 NULL, '12 x 1 pint clamshells',
 1),

('Zucchini — 22 lb',
 'PRD-00019', 'Dark green medium zucchini, harvested at 7–8 inches for optimal flavor and texture. Packed loose in carton.',
 'Hardware', 'Inventory', 1, 'Activated',
 25.00, 'USD', 14.00, 'Box',
 'Flat', 'Standard',
 NULL, '22 lb carton',
 1),

('Mangoes — Tommy Atkins 12 ct',
 'PRD-00020', 'Tommy Atkins mangoes from Mexico and Brazil. Bright red and yellow skin, firm flesh, 12 count tray pack.',
 'Hardware', 'Inventory', 1, 'Activated',
 22.00, 'USD', 13.00, 'Box',
 'Flat', 'Standard',
 NULL, '12 count tray, approx. 12 lb',
 1),

('Garlic — Loose 30 lb',
 'PRD-00021', 'California-grown white garlic, jumbo loose pack. Tight, dry skin for extended shelf life. Strong allicin content.',
 'Hardware', 'Inventory', 1, 'Activated',
 65.00, 'USD', 40.00, 'Box',
 'Flat', 'Standard',
 NULL, '30 lb loose carton',
 1),

('Bananas — 40 lb Case',
 'PRD-00022', 'Chiquita or Dole-grade Cavendish bananas, #4 color (turning). Standard 40 lb case, 4-count cluster pack.',
 'Hardware', 'Inventory', 1, 'Activated',
 19.00, 'USD', 10.50, 'Box',
 'Flat', 'Standard',
 NULL, '40 lb case',
 1),

('Asparagus — 11 lb Pyramid',
 'PRD-00023', 'Fresh green asparagus, pencil to standard diameter. Pyramid pack preserves stalk integrity during transit.',
 'Hardware', 'Inventory', 1, 'Activated',
 42.00, 'USD', 26.00, 'Box',
 'Flat', 'Standard',
 NULL, '11 lb pyramid pack',
 1),

('Corn on the Cob — 48 ct',
 'PRD-00024', 'Sweet yellow corn, husks on, 48 ears per crate. Sugar-enhanced (SE) variety for extended sweetness post-harvest.',
 'Hardware', 'Inventory', 1, 'Activated',
 28.00, 'USD', 16.00, 'Box',
 'Flat', 'Standard',
 NULL, '48-ear crate',
 1),

('Pineapples — Golden Extra Sweet 6 ct',
 'PRD-00025', 'Del Monte Gold Extra Sweet pineapples, 6 count box. High sugar content, low acidity, golden core flesh.',
 'Hardware', 'Inventory', 1, 'Activated',
 24.00, 'USD', 14.00, 'Box',
 'Flat', 'Standard',
 NULL, '6 count box, approx. 20 lb',
 1);
